<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="MassTransit.EntityFrameworkCore" />
    <PackageReference Include="MassTransit.RabbitMQ" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EnglishPath.BuildingBlocks.Application\EnglishPath.BuildingBlocks.Application.csproj" />
  </ItemGroup>
</Project>
