<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\EnglishPath.BuildingBlocks.Domain\EnglishPath.BuildingBlocks.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="EnglishPath.Learning.UnitTests" />
  </ItemGroup>
</Project>
