using EnglishPath.BuildingBlocks.Domain;

namespace EnglishPath.Learning.Domain.Completions;

/// <summary>
/// A server-validated lesson completion. The id is generated by the client so offline syncs
/// can be retried safely (NFR-05); a repeated id is treated as the same completion.
/// </summary>
public sealed class LessonCompletion : AggregateRoot<Guid>
{
    private LessonCompletion()
    {
    }

    public Guid UserId { get; private set; }

    public Guid LessonId { get; private set; }

    public int LessonVersion { get; private set; }

    public int CorrectFirstTry { get; private set; }

    public int TotalExercises { get; private set; }

    public DateOnly LearnerLocalDay { get; private set; }

    public DateTimeOffset CompletedAt { get; private set; }

    public static LessonCompletion Record(
        Guid completionId,
        Guid userId,
        Guid lessonId,
        int lessonVersion,
        int correctFirstTry,
        int totalExercises,
        DateOnly learnerLocalDay,
        DateTimeOffset completedAt)
    {
        ArgumentOutOfRangeException.ThrowIfNegativeOrZero(totalExercises);
        ArgumentOutOfRangeException.ThrowIfNegative(correctFirstTry);
        ArgumentOutOfRangeException.ThrowIfGreaterThan(correctFirstTry, totalExercises);
        return new LessonCompletion
        {
            Id = completionId,
            UserId = userId,
            LessonId = lessonId,
            LessonVersion = lessonVersion,
            CorrectFirstTry = correctFirstTry,
            TotalExercises = totalExercises,
            LearnerLocalDay = learnerLocalDay,
            CompletedAt = completedAt,
        };
    }
}
