<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\EnglishPath.BuildingBlocks.Messaging\EnglishPath.BuildingBlocks.Messaging.csproj" />
    <ProjectReference Include="..\EnglishPath.Progress.Application\EnglishPath.Progress.Application.csproj" />
  </ItemGroup>
</Project>
