using System.Text.Json;
using KidsLang.Application.Abstractions;
using KidsLang.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KidsLang.Infrastructure.Persistence;

public sealed class KidsLangDbContext(DbContextOptions<KidsLangDbContext> options) : DbContext(options), IKidsLangDb
{
    public DbSet<Parent> Parents => Set<Parent>();
    public DbSet<RefreshToken> RefreshTokens => Set<RefreshToken>();
    public DbSet<ChildProfile> ChildProfiles => Set<ChildProfile>();
    public DbSet<LessonProgress> LessonProgress => Set<LessonProgress>();
    public DbSet<ActivityAttempt> ActivityAttempts => Set<ActivityAttempt>();
    public DbSet<QuizAttempt> QuizAttempts => Set<QuizAttempt>();
    public DbSet<ItemMastery> ItemMastery => Set<ItemMastery>();
    public DbSet<Reward> Rewards => Set<Reward>();

    protected override void OnModelCreating(ModelBuilder b)
    {
        var isPostgres = Database.ProviderName?.Contains("Npgsql", StringComparison.Ordinal) == true;

        b.Entity<Parent>(e =>
        {
            e.HasIndex(p => p.Email).IsUnique();
            e.Property(p => p.Email).HasMaxLength(254);
            e.HasMany(p => p.Children).WithOne().HasForeignKey(c => c.ParentId).OnDelete(DeleteBehavior.Cascade);
            e.HasMany(p => p.RefreshTokens).WithOne().HasForeignKey(t => t.ParentId).OnDelete(DeleteBehavior.Cascade);
        });
        b.Entity<RefreshToken>().HasIndex(t => t.TokenHash).IsUnique();
        b.Entity<ChildProfile>(e =>
        {
            e.Property(c => c.Nickname).HasMaxLength(20);
            e.Property(c => c.Avatar).HasJson(isPostgres);
        });
        b.Entity<LessonProgress>(e =>
        {
            e.HasIndex(p => new { p.ChildId, p.LessonId }).IsUnique();
            e.Property(p => p.Status).HasConversion<string>().HasMaxLength(16);
        });
        // Id comes from the client: never generated by the database.
        b.Entity<ActivityAttempt>(e =>
        {
            e.Property(a => a.Id).ValueGeneratedNever();
            e.HasIndex(a => new { a.ChildId, a.LessonId });
        });
        b.Entity<QuizAttempt>(e =>
        {
            e.HasIndex(q => new { q.ChildId, q.LessonId });
            e.Property(q => q.ItemResults).HasJson(isPostgres);
        });
        b.Entity<ItemMastery>(e =>
        {
            e.HasKey(m => new { m.ChildId, m.LearningItemId });
            e.HasIndex(m => new { m.ChildId, m.NextReviewAtUtc });
        });
        b.Entity<Reward>().HasIndex(r => r.ChildId);
    }
}

internal static class JsonColumnExtensions
{
    private static readonly JsonSerializerOptions Options = new(JsonSerializerDefaults.Web);

    /// <summary>JSON value converter: TEXT on SQLite, jsonb on PostgreSQL (portable, no provider SQL).</summary>
    public static PropertyBuilder<T> HasJson<T>(this PropertyBuilder<T> property, bool isPostgres) where T : class, new()
    {
        property.HasConversion(
            v => JsonSerializer.Serialize(v, Options),
            v => JsonSerializer.Deserialize<T>(v, Options) ?? new T(),
            new ValueComparer<T>(
                (a, b) => JsonSerializer.Serialize(a, Options) == JsonSerializer.Serialize(b, Options),
                v => JsonSerializer.Serialize(v, Options).GetHashCode(),
                v => JsonSerializer.Deserialize<T>(JsonSerializer.Serialize(v, Options), Options)!));
        property.HasColumnType(isPostgres ? "jsonb" : "TEXT");
        return property;
    }
}
