<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\EnglishPath.BuildingBlocks.Messaging\EnglishPath.BuildingBlocks.Messaging.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EnglishPath.BuildingBlocks.Persistence\EnglishPath.BuildingBlocks.Persistence.csproj" />
    <ProjectReference Include="..\EnglishPath.Learning.Application\EnglishPath.Learning.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="EnglishPath.Learning.ApplicationTests" />
  </ItemGroup>
</Project>
